### ISSUE TITLE
Sigabrt when running swift on z/os 2.1 / 2.2

### ISSUE THREAD

**Issue by travatine** [IBM-Swift/IBM-Swift-zOS#1]
Hi,

I installed latest version of swift 4 for zos.
I write a swift program consisting of a single print statement.
The program compiles successfully with swiftc compiler.

But, when executed , a Sigabrt RC 131 is issued.

I'm running z/os 2.1 on a z13 box.

Is there any zos or language environment maintenance (PTFs) required to run swift?

( I tried the same steps on a z/os 2.2 lpar on same sysplex and got Sigabrt error)

**Comment by IgorTodorovskiIBM** [comment]
Hi,

Do you have a dump file or better yet, can you run it under /bin/dbx?  

Run your program with `/bin/dbx programname`
Type `run`
Upon sigabort, can you type `where`
If you get a traceback, can you send it to us?

**Comment by travatine** [comment]
Hi ,

I used the example "uselibc"

`$ export LIBPATH=/apc/swiftzos/swift-v4.0.1-201809061453/lib/swift/zos:${LIBPATH}
 /apc/swiftzos/swift-v4.0.1-201809061453/bin/swiftc -g -v  /apc/swiftzos/swift-v4.0.1-
201809061453/examples/uselibc.swift -o uselibc   `

Running with dbx:
`$ LIBPATH=/apc/swiftzos/swift-v4.0.1-201809061453/lib/swift/zos:${LIBPATH} ./uselibc                     
CEE5207E The signal SIGABRT was received.                                                                
[2] - Done(131) LIBPATH=/apc/swiftzos/swift-v4.0.1-201809061453/lib/swift/zos:${LIBPATH} ./uselibc       `
                                                                                                               
Running With dbx:

`$ LIBPATH=/apc/swiftzos/swift-v4.0.1-201809061453/lib/swift/zos:${LIBPATH} /bin/dbx ./uselibc                                                                   
FDBX1111: dbx args: dbx64 ./uselibc                                                                                                                             
FDBX1112: Current Directory: /u/travist                                                                                                                         
FDBX0089: dbx for z/OS with 64-bit support.                                                                                                                     
FDBX0399: Compiled: Aug  6 2015 at 03:58:43 (v2.2) (PROD)                                                                                                       
FDBX0400: OS level: 02.00 02; LE level: 4.2.2; (Local)                                                                                                          
FDBX6499: CDA levels: ELF=D171026.Z2R2, DWARF=D171026.Z2R2,                                                                                                     
                      DDPI=D171026.Z2R2                                                                                                                         
FDBX0100: Type 'help' for help.                                                                                                                                 
FDBX0048: Set an event like 'st in main' then use 'c' to start debugging.                                                                                       
FDBX6432: Processing load module "./uselibc"                                                                                                                    
FDBX9997: The loaded module does not contain module map which may lead to bad performance. Suggest to use dbgld to create module map to the executable before de
bugging.                                                                                                                                                        
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6413: No debug data is available for "./uselibc"                                                                                                   
FDBX0150: Debug target is 64-bit.                                                                                                                               
                                                                                                                                                                
(dbx64) run                                                                                                                                                     
FDBX6432: Processing load module "./uselibc"                                                                                                                    
FDBX9997: The loaded module does not contain module map which may lead to bad performance. Suggest to use dbgld to create module map to the executable before de
bugging.                                                                                                                                                        
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6413: No debug data is available for "./uselibc"                                                                                                   
FDBX6432: Processing load module "/apc/swiftzos/swift-v4.0.1-201809061453/lib/swift/zos/HSZCORE"                                                                
FDBX9997: The loaded module does not contain module map which may lead to bad performance. Suggest to use dbgld to create module map to the executable before de
bugging.                                                                                                                                                        
FDBX6432: Processing load module "/apc/swiftzos/swift-v4.0.1-201809061453/lib/swift/zos/HSZLIBC"                                                                
FDBX9997: The loaded module does not contain module map which may lead to bad performance. Suggest to use dbgld to create module map to the executable before de
bugging.                                                                                                                                                        
FDBX6432: Processing load module "/apc/swiftzos/swift-v4.0.1-201809061453/lib/swift/zos/HSZBSD"                                                                 
FDBX9997: The loaded module does not contain module map which may lead to bad performance. Suggest to use dbgld to create module map to the executable before de
bugging.                                                                                                                                                        
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                      
warning: FDBX6413: No debug data is available for "/apc/swiftzos/swift-v4.0.1-201809061453/lib/swift/zos/HSZBSD"                                                
FDBX6432: Processing load module "/apc/swiftzos/swift-v4.0.1-201809061453/lib/swift/zos/HSZCXX"                                                                 
FDBX9997: The loaded module does not contain module map which may lead to bad performance. Suggest to use dbgld to create module map to the executable before de
bugging.      
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                
warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                
warning: FDBX6423: Unable to resolve source or debug filename from object.              

warning: FDBX6423: Unable to resolve source or debug filename from object.                                                                                   
warning: FDBX6413: No debug data is available for "/apc/swiftzos/swift-v4.0.1-201809061453/lib/swift/zos/HSZCXX"                                             
stopped in CEEOSIGG at 0x000000001806be1c ($t2)                                                                                                              
0x000000001806be1c (???)     a7890000     LGHI    R8,0                                                                                                       
(dbx64) where                                                                                                                                                
CEEOSIGG() at 0x18069fa0, PPA1 at 0x1806cf64, stack at 0x5010af5540                                                                                          
CEEOKILL() at 0x17e3d468, PPA1 at 0x17e3da88, stack at 0x5010af6560                                                                                          
pthread_kill() at 0x17e3dc90, PPA1 at 0x17e40a40, stack at 0x5010af6820                                                                                      
abort() at 0x17c0ca60, PPA1 at 0x17c0cfe8, stack at 0x5010af6920                                                                                             
deftermh() at 0x17e1a3e0, PPA1 at 0x17e20818, stack at 0x5010af6a60                                                                                          
std::terminate()() at 0x196ffab8, PPA1 at 0x19700830, stack at 0x5010af6b60                                                                                  
__cxxinv() at 0x196f5168, PPA1 at 0x196f5700, stack at 0x5010af7520                                                                                          
@@FECBCELQDEST() at 0x196f7058, PPA1 at 0x196f7080, stack at 0x5010af7ee0                                                                                    
__zerrs() at 0x17d101d0, PPA1 at 0x17d125a0, stack at 0x5010af8060                                                                                           
CEEHDSP() at 0x17dd5560, PPA1 at 0x17dda7b8, stack at 0x5010af8160                                                                                           
CEEOSIGG() at 0x18069fa0, PPA1 at 0x1806cf64, stack at 0x5010afb280                                                                                          
CEEHSGL() at 0x17dea490, PPA1 at 0x17deaa68, stack at 0x5010afc2a0                                                                                           
doThrow() at 0x1951e7e8, PPA1 at 0x1951f738, stack at 0x5010afc5c0                                                                                           
__cxa_rethrow() at 0x1951ed80, PPA1 at 0x1951f810, stack at 0x5010afc6c0                                                                                     
std::__1::random_device::random_device(std::__1::basic_string<char, std::__1::char_traits<c...() at 0x1946e370, PPA1 at 0x1946f530, stack at 0x5010afc7c0    
randomUInt64()() at 0x1855b4a8, PPA1 at 0x1855bc38, stack at 0x5010afd300                                                                                    
static-initialization-fn() at 0x1855baf8, PPA1 at 0x1855be40, stack at 0x5010afde40                                                                          
cxxctor() at 0x17c58120, PPA1 at 0x17c584a8, stack at 0x5010afdf40                                                                                           
statcnst() at 0x17c57900, PPA1 at 0x17c58408, stack at 0x5010afe040                                                                                          
CEEZIDT() at 0x17e15a70, PPA1 at 0x17e169a8, stack at 0x5010afe140                                                                                           
CELQINMN() at 0x17e23640, PPA1 at 0x17e25cf8, stack at 0x5010afe920                                                                                          
CELQINIT() at 0x17bd9010, PPA1 at 0x17bdafac, stack at 0x5010aff220                                                                                                                                                                                                                                                                                                              
`

**Comment by IgorTodorovskiIBM** [comment]
Thank you for the details!  We suspect the issue is that ICSF is not running on your system.  One way to workaround it is to turn on ICSF on your system.

We also have a patch that we are testing that will not require ICSF turned on and hope to have it ready fairly soon.  We'll keep you updated.

**Comment by travatine** [comment]
Hi,

Thanks, after getting ICSF setup and running we can now successfully run swift programs.

Kind Regards,
Travis Thorne

**Comment by IgorTodorovskiIBM** [comment]
Great,

We have refreshed the download package with a patch that should resolve the issue as well.

**Comment by travatine** [comment]
Hi,
Thanks, 
I've asked our Sysprogs to install the fix on our LPARs.
I'll test it out once its applied.

Kind Regards,
Travis Thorne.
