### ISSUE TITLE
Compiler abends version swift-v4.2.1-201902261740 on Z/OS 2.2

### ISSUE THREAD

**Issue by tdemonbreum** [IBM-Swift/IBM-Swift-zOS#5]
Just downloaded and installed swift and doing a swiftc -v results in:

CEE3561S External function get_new_handler__3stdFv was not found in DLL CELQDCPP.                                                   
         From compile unit TOROLABA:../src/exception.cpp/ at entry point std::set_terminate(void (*)()) at statement 84 at compile u
nit offset +00000000319B7B3C at entry offset +0000000000000054 at address 00000000319B7B3C.                                         
LEAID201I - LEAID64 ENTERED (LEVEL 12/05/2016 12.37 PTF-PT00159).                                                                   
LEAID207I - LEAID64 RETURN FROM ABEND-AID, RC=0.                                                                                    
Ý1¨ + Done(137) swiftc -v                                                                                                           
  83886763      Killed  /opt/swift/swift-v4.2.1-201902261740/bin/swiftc

**Comment by IgorTodorovskiIBM** [comment]
std::set_terminate is defined in DLL: <swift_install_path>/lib/swift/zos/HSZCXX.  
```
nm HSZCXX | grep set_terminate
330552 T _ZSt13set_terminatePFvvE
```

Can you give us some more information on your system specifications, such as the architecture level.  Are you on a z14, z13 or ec12 machine?

**Comment by tdemonbreum** [comment]
This is a z14 ZR1.

Thanks

**Comment by IgorTodorovskiIBM** [comment]
Hi,

Do you have the latest LE PTFs installed on the system?

You may be able to workaround it by copying <install_path>/lib/swift/zos/HSZSCPP to <install_path>/lib/swift/zos/CELQDCPP

**Comment by tdemonbreum** [comment]
That got it working.  Thanks.

No, I’m a little back on LE maintenance.  Are there specific PTFs you know of?
There will be some LE maintenance going on probably this next weekend for support COBOL 6.x so if there are
more fixes that need to be on for Swift please pass them along.


Thanks again
